import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css'; // 전체 공통 스타일
import styles from './page.module.css'; // 특정 페이지용

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className={styles.container}>{children}</div>
			</body>
		</html>
	);
}
